### ISSUE TITLE
npm run dev is broken

### ISSUE THREAD

**Issue by flaminisx** [rsuite/rsuite-management-system#3]
I tried to run `npm run dev` and got an error:
```
rsuite-management-system/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                                                     ^

TypeError: Cannot read property 'properties' of undefined
```

steps to reproduce:
1. clone repository
2. `npm i`
3. `npm run dev`

**Comment by xiejun** [comment]
> I tried to run `npm run dev` and got an error:
> 
> ```
> rsuite-management-system/node_modules/webpack-cli/bin/config-yargs.js:89
> 				describe: optionsSchema.definitions.output.properties.path.description,
> 				                                                                     ^
> 
> TypeError: Cannot read property 'properties' of undefined
> ```
> 
> steps to reproduce:
> 
> 1. clone repository
> 2. `npm i`
> 3. `npm run dev`

migrating to latest version solved the error for me: webpack-cli@3.1.1
https://github.com/webpack/webpack-cli/issues/607

**Comment by ha23r** [comment]
npm run still fails

> webpack-dev-server --mode development --progress --hot

C:\dev\temp\rsuite-management-system-master\node_modules\webpack-cli\bin\config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (C:\dev\temp\rsuite-management-system-master\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at Object.<anonymous> (C:\dev\temp\rsuite-management-system-master\node_modules\webpack-dev-server\bin\webpack-dev-server.js:65:25)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rsuite-management-system@1.0.0 dev: `webpack-dev-server --mode development --progress --hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rsuite-management-system@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hemia\AppData\Roaming\npm-cache\_logs\2020-04-13T18_18_05_642Z-debug.log

any solution?

**Comment by simonguo** [comment]
webpack and rsuite have been upgraded to the latest version, try again.
